---
dist: trusty
language: python
python:
  - "3.6"

services:
  - docker

env:
  global:
    - ROLE_NAME: java
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

before_install:
  - sudo apt-get -qq update

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME nuevolia.$ROLE_NAME
  - cd nuevolia.$ROLE_NAME
  - pip install -r requirements.txt

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
